apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  azure_client_id: MmRlYWExNmMtZGE1Zi00MDY3LWI4NTYtZTI4NGQ0ODk2NjU2
  azure_tenant_id: ZTYzMDJhYTctNjM2Mi00MGJmLWIzNDUtOGI0NTU1ZjE4ZTUw
  azure_client_secret: TzdSOFF+cjg4YW16Sms3d1gxc3Rxfjl0Q3FWV1lMZzNYX0dkTGN+MA==
  azure_subscription_id: ZDI5OTdjM2EtODVhMy00ZDFmLWJhN2MtZTBhYTlmZWE1ZDFl